contact/urls.py
from re import search
from django.contrib import admin
from django.urls import path
from contact import views


app_name = 'contact'

urlpatterns = [
    path('', views.index, name="index"),
    path('users-json/', views.users_json, name='users'),
    path('search/', views.search, name='search'),
    
    path('contact/<int:id>/', views.user_detail, name='user'),
    path('contact/create/', views.create, name='create'),
    path('contact/update/<int:id>/', views.update, name='update'),
    path('contact/delete/<int:id>/', views.delete, name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("contact.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categories'
        
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    phone = models.CharField(max_length=60)
    email = models.EmailField(max_length=254, blank=True) 
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%y/%m')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from . import models
from django import forms
from django.core.exceptions import ValidationError

class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ("first_name", "last_name", "phone", "email")
        
    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        
        if first_name == last_name:
            msg = ValidationError("Primeiro nome não pode ser igual ao segundo nome", code="invalid")
            self.add_error("first_name", msg)
            self.add_error("last_name", msg)

        return super().clean()
            

contact/views.py
# from curses import flash
from urllib import request
from django.http import JsonResponse, response, HttpRequest, HttpResponse
from typing import Any
from django.shortcuts import render
from . models import Contact

# Create your views here.
def index(request):
    return render(
        request,
        'contact/index.html',
    )
    
class Users:
    def __init__(self):
        #return users at function
        self.all_users: list[dict[str, Any]] = list(Contact.objects.values())

    def return_all_users(self, request: HttpRequest) -> HttpResponse:
        print(self.all_users)
        
        return JsonResponse(self.all_users, safe=False)

def users_view(request: HttpRequest) -> HttpResponse:
    print("Chegou aqui")
    return render(
        request,
        'contact/index.html',
    )
    return Users().return_all_users(request)

contact/views/contact_forms.py
from django.db.models import QuerySet, Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from contact.forms import ContactForm
from contact.models import Contact


# Create your views here.
def create(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("contact:index")
        context = {'form': form, "title": "Criar Contato"}
        return render(request,'contact/create.html', context)
    
    context = {'form': ContactForm()}
    return render(request,'contact/create.html', context)
    
def update(request, id):
    contact = get_object_or_404(Contact, id=id)
    
    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect("contact:users")  
        context = {'form': form, 'contact': contact, "title": "Atualizar Contato"}
        return render(request, 'contact/update.html', context)
    
    form = ContactForm(instance=contact)
    context = {'form': form, 'contact': contact, "title": "Atualizar Contato"}
    return render(request, 'contact/create.html', context)   

def delete(request, id):
    contact = get_object_or_404(Contact, id=id)

    if request.method == "POST":
        contact.delete()
        return redirect("contact:users")  # depois de deletar, volta pra listagem

    context = {"contact": contact}
    return render(request, "contact/delete_confirm.html", context)

contact/views/contact_views.py
from django.db.models import QuerySet, Q
from django.http import HttpRequest, HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
import contact
from ..models import Contact

# Create your views here.
def index(request):
    return render(request,'contact/index.html')
    
class Users:
    def __init__(self, param=None, search=None):
        self.all_users: Contact = Contact.objects.all().order_by('-id')
        if param:
            self.user: Contact = get_object_or_404(Contact, pk=param)
        elif search:
            self.result_search: contact = \
            Contact.objects.filter(Q(first_name__icontains=search) | 
            Q(last_name__icontains=search) | 
            Q(email__icontains=search) |     
            Q(description__icontains=search))    

    def users_view(self, request: HttpRequest) -> HttpResponse:
        contacts = self.all_users
        paginator = Paginator(contacts, 10)
        page_number = request.GET.get("page")
        page_object = paginator.get_page(page_number)
        context = {
            "page_object": page_object,
        }
        return render(request, "contact/home.html", context=context)
    
    def user_view(self, request: HttpRequest) -> HttpResponse:
        return render(request, "contact/contact.html", context={"contact": self.user})
    
    def user_search(self, request: HttpRequest) -> HttpResponse:
        contacts = self.result_search
        paginator = Paginator(contacts, 10)
        page_number = request.GET.get("page")
        page_object = paginator.get_page(page_number)
        context = {
            "page_object": page_object,
        }
        return render(request, "contact/home.html", context=context)


def users_json(request: HttpRequest) -> HttpResponse:
    return Users().users_view(request)

def user_detail(request: HttpRequest, id: int) -> HttpResponse:
    return Users(id).user_view(request)

def search(request: HttpRequest) -> HttpResponse:
    value_search = request.GET.get("q").strip()
    if value_search == '':
        return redirect('contact:users')
    print(value_search)
    return Users(search=value_search).user_search(request)

contact/templates/contact/contact.html
{% extends "global/base.html" %}
{% block content %}
<div class="user-details-container">
    <div class="user-details-card">
        <h1 class="user-name">{{ contact.first_name }} {{ contact.last_name }}</h1>
        <div class="user-info">
            <p><span>📞 Telefone:</span> {{ contact.phone }}</p>
            <p><span>📧 E-mail:</span> {{ contact.email }}</p>
            <p><span>📝 Descrição:</span></p>
            <p class="user-description">{{ contact.description }}</p>
        </div>

        <div class="buttons-form" style="display:flex; gap:10px;">
            <a href="{% url 'contact:users' %}" class="back-button">Voltar</a>
            <a href="{% url 'contact:update' contact.id %}" class="back-button">Atualizar</a>

            <!-- Form de exclusão -->
            <form method="post" action="{% url 'contact:delete' contact.id %}" style="display:inline;">
                {% csrf_token %}
                <button style="border: None; height: 5.4vh;" type="submit" class="back-button" style="background-color:#d9534f;">
                    Excluir
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}
{% load static %}

{% block content %}
<div class="form-container">
    <div class="form">
        <h2 class="create_title">{{ title }}</h2>
        <form method="post" class="space">
            {% csrf_token %}
            {% for field in form %}
                <div class="block_orientation">
                    <label class="labels" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}

                    {{ field.errors }}
                </div>
            {% endfor %}
            <div class="buttons-form">
                <button type="submit" class="form-button">Salvar</button>
                <button type="reset" class="form-button">Limpar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

contact/templates/contact/home.html
{% extends "global/base.html" %}
{% load static %}
{% block content %}
<div class="users-container">
    {% if page_object %}
        <table class="users-table">
            <thead>
                <tr >
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for user in page_object %}
                <tr>
                    <td><a href="{% url "contact:user" user.id %}" class="user-link">{{ user.id }}</a></td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.phone }}</td>
                    <td>{{ user.email }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div>
            <h1 style="color: white; font-size: 4vh;">Users Not Found</h1>
        </div>
        {% endif %}
    </div>
{% include "global/partials/_paginator.html" %}
{% endblock content %}

contact/templates/contact/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "global/css/style.css" %}">
    <title>Document</title>
</head>
<body>
    <div>
        <div class="very-form">
            <div  style="display: flex; align-items: center; width: 50%; flex-direction: column; margin-top: 70px;">
                <label style="font-size: 4vh; font-weight: bold;" class="labels">Welcome</label>
                <label style="font-size: 3.5vh; font-weight: 300;" class="labels">Task Manager</label>
            </div>
    
            <form for="" id="userForm" class="form", action="{% url 'contact:users' %}" method="get">
                <div class="space">
                    <label style="margin-bottom: 20px;" class="create_title">Create Account</label>
    
                    <div style="align-items: center; display: flex; flex-direction: column; gap: 5px;">
                        <div class="block_orientation">    
                            <label class="labels" for="login-id">Login</label>
                            <input id="login-id" name="username" class="inputs_form" type="text">                            
                        </div>    
                        <div class="block_orientation">    
                            <label class="labels" for="password-id">Senha</label>
                            <input type="password" id="password-id" name="password" class="inputs_form">
                        </div>
                    </div>
    
                    <label style="color: white; font-weight: lighter; font-size: 1.3vh; text-decoration: underline; cursor: pointer;">
                        Esqueci minha senha
                    </label>
    
                    <div class="buttons-form">
                        <button id="loginBtn" type="submit" class="form-button">Login</button>
                        <button type="submit" class="form-button">Register</button>
                    </div>
                </div>
            </form>
        </div>
        <script 
            src="{% static 'global/scripts/script.js' %}">
        </script>
    </div>
</body>
</html>